### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by kkholbekov** [nciske/salesforce-wordpress-to-lead#102]
Dear Support Team,

Could you please help us with spam issue:
Even with Captcha enabled(Google), we are receiving spam(screenshot attached).

Brilliant salesforce-wordpress-to-lead Plugin is latest updated (Version 2.7.3.9 ).
Wordpress (Version 5.5.1) is also latest updated.

Thanks
Best Regards,

![Brilliant salesforce-wordpress-to-lead](https://user-images.githubusercontent.com/64146683/93012458-99687e00-f5b1-11ea-8e21-6a5e48daa3d8.png)

**Comment by nciske** [comment]
Please post in the WordPress support forum for assistance, thanks!
https://wordpress.org/support/plugin/salesforce-wordpress-to-lead/
