### ISSUE TITLE
1 Hour Delay - Creating a Lead in Salesforce

### ISSUE THREAD

**Issue by kkholbekov** [nciske/salesforce-wordpress-to-lead#103]
Dear Support Team,

Could you please help us:
We are facing issue of Lead Creation with delay of exactly 1 hour.
Example: Once Contact Form(salesforce-wordpress-to-lead) is submitted, the Lead is creating in our Salesforce exactly after 1 hour.
This issue started just recently, few days ago.

Thanks
Best Regards,

**Comment by nciske** [comment]
Talk to Salesforce -- then plugin sends the data upon submission.
