### ISSUE TITLE
WEB TO LEAD Contact form is not generating lead, sending mails but not adding to the leads list in WordPress

### ISSUE THREAD

**Issue by prasenpatilgit** [nciske/salesforce-wordpress-to-lead#104]
Hi team,

WEB TO LEAD Contact form is not generating lead, sending mails but not adding to the leads list in WordPress.
Stuck here from many days.
Help is appreciated.

**Comment by nciske** [comment]
**If it's sending an email, it has already sent the data to SF (emails are sent after the POST to SF).**

Whether SF accepts it... is another matter entirely.

This is _almost always_ a configuration issue between your form & Salesforce account.
_Sometimes_ it's an old version of Curl.

But this is not the place for that type of support.

Please post in the WordPress support forum for assistance, thanks!
https://wordpress.org/support/plugin/salesforce-wordpress-to-lead/
