### ISSUE TITLE
How can you have required select lists without a default value?

### ISSUE THREAD

**Issue by jimpdx** [nciske/salesforce-wordpress-to-lead#106]
It looks to me like using the "Placeholder" label display might be my only option here, but we would like our required "Select (picklist)" to start with a "Select One...." type initial value, but then validate that they have selected an option from the list. We think our web leads are not bothering to actually select a value and leaving the defaults, based on the qualifying questions we ask via phone or email:

![image](https://user-images.githubusercontent.com/867051/109564537-102d0100-7a96-11eb-9551-acc7dd9aa39e.png)

**Comment by nciske** [comment]
From the [FAQ](https://wordpress.org/plugins/salesforce-wordpress-to-lead/#how%20do%20i%20use%20the%20select%20(picklist)%20field%3F).

```
// Use different data for display and value passed to SF, and/or require user to select something (assuming field is required)
Select One|
name1|value1
name2|value2
```
