### ISSUE TITLE
Web to lead stopped working?

### ISSUE THREAD

**Issue by Teunski** [nciske/salesforce-wordpress-to-lead#107]
Hello,

We are using web to lead, for over five years now. Always has been working perfectly fine untill now. No one within the organization has an idea why, since we didn't make any changed either to salesforce or to our website.

Truly looking for a solution, after going through the fora and documentation of salesforce.
We're not receiving any leads in salesforce anymore, but the forms are being filled in and we're receiving a succes page as it should.

Desperately looking for an answer.

All the best!

**Comment by nciske** [comment]
Nothing has changed in the plugin. You can use the debug settings in the readme to see if Salesforce can tell you why leads aren't being accepted... and if that doesn't work, check your captcha settings -- it should not be enabled at Salesforce, the plugin uses an independent implementation.

**Comment by Teunski** [comment]
Thanks for the quick response Nick, problem solved. Issue was indeed in the Captcha settings in Salesforce. It was checked by a coworker, I have unchecked it.  Thanks and keep up the good work!
