### ISSUE TITLE
Disappearing Text

### ISSUE THREAD

**Issue by laura13015** [nciske/salesforce-wordpress-to-lead#108]
I recently started using the Brilliant plugin on my Kadence WP site. However, on the site when I type in my test data on the form, it disappears when I move to the next space. 

It does not do this if I select the content from pre-filled options. Below is a link to a video that I made of the issues so that it would be easier to understand. 

I need to use this on my website so would appreciate any insight that you can give as to the cause of this issue. 

https://youtu.be/nGD2QkQG8qo

Thank you,
Laura

**Comment by nciske** [comment]
The plugin renders a standard web form. There is nothing active happening (in the plugin) --  so this is almost entirely related to your theme or a plugin (or your browser).

Unfortunately, I cannot diagnose it further based solely on a video.

**Comment by laura13015** [comment]
Okay thanks.


[photo-logo]
Laura Strait
Marketing Director

Laundry Equipment Services, Inc.

p: 800-866-6905 ext. 115
w: www.leslaundry.com<https://img.newoldstamp.com/r/4755/w>
e: ***@***.******@***.***>
a: 13015 Salem Ave., Hagerstown, MD 21740

[facebook]<https://img.newoldstamp.com/r/4755/facebook> [linkedin] <https://img.newoldstamp.com/r/4755/linkedin>


[cid:62ec7db3-be7c-4549-bd86-d20e92299801]<tel:18008666905>

________________________________
