### ISSUE TITLE
Content-type

### ISSUE THREAD

**Issue by gregrowe1231** [nciske/salesforce-wordpress-to-lead#26]
I'm using WP 4.0 on Debian Wheezy.  Php version is 5.4.35.

The plugin would not generate leads for me until I added a Content-Type header.

Line 548 of salesforce.php:
'Content-Type' => 'application/x-www-form-urlencoded'

With the addition of that everything works perfectly.

**Comment by nciske** [comment]
Released in precious version. Closing.

**Comment by nciske** [comment]
Or previous. Autocorrect #fail.
