### ISSUE TITLE
Plugin Sending Emails without content

### ISSUE THREAD

**Issue by cheesehead22** [nciske/salesforce-wordpress-to-lead#28]
Within 24 hours of installing this plugin and setting up my first form I have received the following email 30+ times:

Subject : "Salesforce Web to Lead Submission"

Content:  "Lead Source: Web comment, http://youthoncourse.org"

And that's it. It's just super annoying and filling up my inbox. Im not sure how or what is generating the email but Im guessing it is this plugin and some sort of setting. Just for context my company website is the one listed as the web comment in the content of the email. Id just really like to not get 40 emails a day that have nothing in them!

Thanks,
Lindsey

**Comment by nciske** [comment]
It's a spam submission. That's what the captcha is for.

**Comment by nciske** [comment]
Oh wait... you must have the comments to leads integration enabled. Turn that off, or fix your comment spam problem ;-)

**Comment by cheesehead22** [comment]
Thanks so much! Hopefully it's fixed! Thanks
