### ISSUE TITLE
Submit form resolves user to home screen if on alternate page when form is submitted

### ISSUE THREAD

**Issue by mpbfamily** [nciske/salesforce-wordpress-to-lead#33]
We have form in multiple areas of the site.  Where ever it is located, we would like the the submit button to register as if the form was filled out from the home landing page.  Is this possible

**Comment by nciske** [comment]
Support for this plugin is via the WordPress.org support forum. Please resubmit your question there. 

https://wordpress.org/support/plugin/salesforce-wordpress-to-lead

GitHub issues are for bug reports only.

Also, I'm unclear what you're asking so please rephrase and/or give me some specific examples or urls to view.
