### ISSUE TITLE
Lead Source is not showing up in Sales force 

### ISSUE THREAD

**Issue by bricegould** [nciske/salesforce-wordpress-to-lead#38]
I have this: %www.plansource.com/contact% entered into my lead source field and nothing is showing up in salesforce.

I'm currently on version 2.7 and I'm not subscribed to Daddy Analytics.

Could this be a problem on Salesforce side or with the plug-in?

**Comment by nciske** [comment]
You need to use `%URL%` exactly. The plugin does a replacement at the time of submission.

*FYI*

Free support is handled via the WP.org forums:
http://wordpress.org/support/plugin/salesforce-wordpress-to-lead

If you want one on one support — we offer that as well:
https://cimbura.com/tech/support/premium-plugin-support/
