### ISSUE TITLE
Capturing the HTTP referrer value?

### ISSUE THREAD

**Issue by jimpdx** [nciske/salesforce-wordpress-to-lead#41]
I would like to capture which page has the lead form on it so I know which page the user filled out the form. Could I somehow reference a PHP variable in a hidden lead input field with a value like <? $_SERVER['HTTP_REFERER'] ?>

**Comment by nciske** [comment]
Read the [FAQ](https://wordpress.org/plugins/salesforce-wordpress-to-lead/faq/)

Specifically this question: *I want to include the full URL the form is embedded on, but SF limits the lead source to 40 characters -- how would I do that?*
